### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by MitchK** [jmcarp/py-cfenv#4]
When I install the latest package in my virtual env, using Python 3.2, I get:

```
Downloading/unpacking cfenv==0.5.2 (from -r requirements.txt (line 4))
  Downloading cfenv-0.5.2.tar.gz
  Running setup.py egg_info for package cfenv
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/travis/build/app/app/component/venv/build/cfenv/setup.py", line 44, in <module>
        license=read('LICENSE'),
      File "/home/travis/build/app/app/component/venv/build/cfenv/setup.py", line 28, in read
        with open(fname) as fp:
    IOError: [Errno 2] No such file or directory: 'LICENSE'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/home/travis/build/app/app/component/venv/build/cfenv/setup.py", line 44, in <module>
    license=read('LICENSE'),
  File "/home/travis/build/app/app/component/venv/build/cfenv/setup.py", line 28, in read
    with open(fname) as fp:
IOError: [Errno 2] No such file or directory: 'LICENSE'
```

**Comment by MitchK** [comment]
Seems like it will probably be fixed here:
https://github.com/jmcarp/py-cfenv/pull/3
